#!/bin/bash
export HOSTNAME=$(hostname)
export TIMEZONE=$(timedatectl | grep Time | awk '{print $3 $4 $5}')
export USER=$(whoami)
export OS=$(cat /etc/issue)
export DATE=$(date "+%d %B %Y %H:%M:%S")
export UPTIME=$(uptime -p)
export UPTIME_SEC=$(cat /proc/uptime | awk '{print $1}')
export IP=$(hostname -I |  awk '{print $1}')
export MASK=$(ifconfig | grep inet | grep netmask | awk 'NR==1 {printf $4}')
export GATEWAY=$(ip -4 route show default | awk '{print $3}')
export RAM_TOTAL=$(free --mega | awk '/Mem/ {printf "%.3f GB", $2/1024}')
export RAM_USED=$(free --mega | awk '/Mem/ {printf "%.3f GB", $3/1024}')
export RAM_FREE=$(free --mega | awk '/Mem/ {printf "%.3f GB", $4/1024}')
export SPACE_ROOT=$(df --output=size / | tail -n 1 | awk '{printf "%.2f MB", $1/1024/1024}')
export SPACE_ROOT_USED=$(df --output=used / | tail -n 1 | awk '{printf "%.2f MB", $1/1024/1024}')
export SPACE_ROOT_FREE=$(df --output=avail / | tail -n 1 | awk '{printf "%.2f MB", $1/1024/1024}')
